In [2]:
import numpy as np

In [3]:
import pandas as pd

In [5]:
dataset = pd.read_csv("C:/Users/ADMIN/Desktop/FBS/Data Analysis/data set/cars93.csv")
dataset

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,Driver & Passenger,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,Driver & Passenger,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,Driver & Passenger,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [9]:
dataset.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         79 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [12]:
dataset.shape          # (row, column)

(93, 10)

In [13]:
dataset.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           14
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [14]:
dataset[dataset["Rear.seat.room"].isna()]

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
18,Chevrolet,Corvette,Sporty,38.0,17,Driver only,300,2,NaN,NaN
56,Mazda,RX-7,Sporty,32.5,17,Driver only,255,2,NaN,NaN

In [16]:
dataset["AirBags"].mode()

0    Driver only
Name: AirBags, dtype: object

In [17]:
dataset["AirBags"] = dataset["AirBags"].fillna("Driver only")

In [19]:
dataset.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags            0
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

In [20]:
dataset["Luggage.room"].mean()

np.float64(13.890243902439025)

In [6]:
dataset.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,Driver only,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [8]:
dataset["Type"].unique

<bound method Series.unique of 0       Small
1     Midsize
2     Compact
3     Midsize
4     Midsize
       ...
88        Van
89    Compact
90     Sporty
91    Compact
92    Midsize
Name: Type, Length: 93, dtype: object>

In [9]:
dataset["Type"].nunique

<bound method IndexOpsMixin.nunique of 0       Small
1     Midsize
2     Compact
3     Midsize
4     Midsize
       ...
88        Van
89    Compact
90     Sporty
91    Compact
92    Midsize
Name: Type, Length: 93, dtype: object>

In [10]:
dataset["Type"].value_counts

<bound method IndexOpsMixin.value_counts of 0       Small
1     Midsize
2     Compact
3     Midsize
4     Midsize
       ...
88        Van
89    Compact
90     Sporty
91    Compact
92    Midsize
Name: Type, Length: 93, dtype: object>

In [ ]:
# employee.loc[len(employee)]=[6,"Dipali",34000,"Mumbai"]