In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-2.3.0-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.0-cp312-cp312-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.0 MB 2.0 MB/s eta 0:00:06
   ---------------------------------------- 0.0/11.0 MB 2.0 MB/s eta 0:00:06
   ---------------------------------------- 0.1/11.0 MB 550.5 kB/s eta 0:00:20
   ---------------------------------------- 0.1/11.0 MB 550.5 kB/s eta 0:00:20
   ---------------------------------------- 0.1/11.0 MB 353.1 kB/s eta 0:00:31
    --------------------------------------- 0.1/11.0 MB 532.5 kB/s eta 0:00:21
    --------------------------------------- 0.1/11.0 MB 532.5 kB/s eta 0:00:21
    --------------------------------------- 0.2/11.0 MB 477.7 kB/s eta 0:00:23
    --------------------------------------- 0.2/11.0 MB 573.4 kB/s eta 0:00:19
   - -------------------------------------- 0.3/11.0 MB 656.1 kB/s eta 0:00:17
   - -------------------------------------- 0.4/11.0 MB 740.5 kB/s eta 0:00:15
   - -------------------------------------- 0.4/11.0 MB 737.3 kB/s eta 0:00:15
   - -------------------------------------- 0.4/11.0 MB 726.4 kB/s eta 0:00:15
   - -------------------------------------- 0.5/11.0 MB 786.4 kB/s eta 0:00:14
   -- ------------------------------------- 0.6/11.0 MB 858.5 kB/s eta 0:00:13
   -- ------------------------------------- 0.6/11.0 MB 815.7 kB/s eta 0:00:13
   -- ------------------------------------- 0.6/11.0 MB 803.1 kB/s eta 0:00:13
   -- ------------------------------------- 0.6/11.0 MB 799.8 kB/s eta 0:00:13
   -- ------------------------------------- 0.7/11.0 MB 822.5 kB/s eta 0:00:13
   -- ------------------------------------- 0.7/11.0 MB 846.4 kB/s eta 0:00:13
   -- ------------------------------------- 0.8/11.0 MB 795.1 kB/s eta 0:00:13
   --- ------------------------------------ 0.8/11.0 MB 832.5 kB/s eta 0:00:13
   --- ------------------------------------ 0.9/11.0 MB 844.2 kB/s eta 0:00:12
   --- ------------------------------------ 0.9/11.0 MB 852.6 kB/s eta 0:00:12
   --- ------------------------------------ 0.9/11.0 MB 852.6 kB/s eta 0:00:12
   --- ------------------------------------ 1.0/11.0 MB 821.3 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/11.0 MB 828.2 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/11.0 MB 828.2 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/11.0 MB 772.7 kB/s eta 0:00:13
   --- ------------------------------------ 1.1/11.0 MB 793.0 kB/s eta 0:00:13
   ---- ----------------------------------- 1.2/11.0 MB 830.3 kB/s eta 0:00:12
   ---- ----------------------------------- 1.2/11.0 MB 819.5 kB/s eta 0:00:12
   ---- ----------------------------------- 1.2/11.0 MB 798.7 kB/s eta 0:00:13
   ---- ----------------------------------- 1.2/11.0 MB 794.3 kB/s eta 0:00:13
   ---- ----------------------------------- 1.2/11.0 MB 794.3 kB/s eta 0:00:13
   ---- ----------------------------------- 1.3/11.0 MB 754.4 kB/s eta 0:00:13
   ---- ----------------------------------- 1.3/11.0 MB 746.6 kB/s eta 0:00:14
   ---- ----------------------------------- 1.3/11.0 MB 749.0 kB/s eta 0:00:13
   ----- ---------------------------------- 1.4/11.0 MB 770.4 kB/s eta 0:00:13
   ----- ---------------------------------- 1.5/11.0 MB 795.4 kB/s eta 0:00:12
   ----- ---------------------------------- 1.5/11.0 MB 802.8 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/11.0 MB 815.1 kB/s eta 0:00:12
   ------ --------------------------------- 1.7/11.0 MB 848.1 kB/s eta 0:00:11
   ------ --------------------------------- 1.8/11.0 MB 874.1 kB/s eta 0:00:11
   ------ --------------------------------- 1.9/11.0 MB 903.8 kB/s eta 0:00:11
   ------ --------------------------------- 1.9/11.0 MB 901.8 kB/s eta 0:00:11
   ------- -------------------------------- 2.0/11.0 MB 907.2 kB/s eta 0:00:10
   ------- -------------------------------- 2.1/11.0 MB 929.6 kB/s eta 0:00:10
   ------- -------------------------------- 2.2/11.0 MB 955.7 kB/s eta 0:00:10
   -------- ------------------------------- 2.3/11.0 MB 985.2 kB/s eta 0:00:09
   -------- ------------------------------- 2.3/11.0 MB 987.7 kB/s eta 0:00:09
   -------- ------------------------------- 2.4/11.0 MB 1.0 MB/s eta 0:00:09
   --------- ------------------------------ 2.5/11.0 MB 1.0 MB/s eta 0:00:09
   --------- ------------------------------ 2.6/11.0 MB 1.1 MB/s eta 0:00:08
   --------- ------------------------------ 2.7/11.0 MB 1.1 MB/s eta 0:00:08
   ---------- ----------------------------- 2.8/11.0 MB 1.1 MB/s eta 0:00:08
   ---------- ----------------------------- 2.8/11.0 MB 1.1 MB/s eta 0:00:08
   ---------- ----------------------------- 2.9/11.0 MB 1.1 MB/s eta 0:00:08
   ---------- ----------------------------- 2.9/11.0 MB 1.1 MB/s eta 0:00:08
   ---------- ----------------------------- 2.9/11.0 MB 1.1 MB/s eta 0:00:08
   ----------- ---------------------------- 3.1/11.0 MB 1.1 MB/s eta 0:00:08
   ----------- ---------------------------- 3.2/11.0 MB 1.1 MB/s eta 0:00:07
   ----------- ---------------------------- 3.2/11.0 MB 1.1 MB/s eta 0:00:07
   ----------- ---------------------------- 3.2/11.0 MB 1.1 MB/s eta 0:00:08
   ----------- ---------------------------- 3.2/11.0 MB 1.1 MB/s eta 0:00:08
   ------------ --------------------------- 3.3/11.0 MB 1.1 MB/s eta 0:00:08
   ------------ --------------------------- 3.3/11.0 MB 1.1 MB/s eta 0:00:08
   ------------ --------------------------- 3.4/11.0 MB 1.1 MB/s eta 0:00:08
   ------------ --------------------------- 3.4/11.0 MB 1.1 MB/s eta 0:00:07
   ------------ --------------------------- 3.5/11.0 MB 1.1 MB/s eta 0:00:07
   ------------- -------------------------- 3.6/11.0 MB 1.1 MB/s eta 0:00:07
   ------------- -------------------------- 3.6/11.0 MB 1.1 MB/s eta 0:00:07
   ------------- -------------------------- 3.7/11.0 MB 1.1 MB/s eta 0:00:07
   ------------- -------------------------- 3.7/11.0 MB 1.1 MB/s eta 0:00:07
   ------------- -------------------------- 3.7/11.0 MB 1.1 MB/s eta 0:00:07
   ------------- -------------------------- 3.8/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 3.9/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.0/11.0 MB 1.1 MB/s eta 0:00:07
   -------------- ------------------------- 4.1/11.0 MB 935.0 kB/s eta 0:00:08
   -------------- ------------------------- 4.1/11.0 MB 935.0 kB/s eta 0:00:08
   --------------- ------------------------ 4.3/11.0 MB 962.6 kB/s eta 0:00:07
   --------------- ------------------------ 4.3/11.0 MB 962.6 kB/s eta 0:00:07
   --------------- ------------------------ 4.3/11.0 MB 947.2 kB/s eta 0:00:08
   --------------- ------------------------ 4.4/11.0 MB 947.5 kB/s eta 0:00:07
   --------------- ------------------------ 4.4/11.0 MB 942.3 kB/s eta 0:00:07
   ---------------- ----------------------- 4.4/11.0 MB 935.1 kB/s eta 0:00:08
   ---------------- ----------------------- 4.4/11.0 MB 931.3 kB/s eta 0:00:08
   ---------------- ----------------------- 4.4/11.0 MB 927.4 kB/s eta 0:00:08
   ---------------- ----------------------- 4.5/11.0 MB 926.1 kB/s eta 0:00:07
   ---------------- ----------------------- 4.6/11.0 MB 930.9 kB/s eta 0:00:07
   ---------------- ----------------------- 4.6/11.0 MB 928.3 kB/s eta 0:00:07
   ---------------- ----------------------- 4.6/11.0 MB 932.4 kB/s eta 0:00:07
   ---------------- ----------------------- 4.7/11.0 MB 921.1 kB/s eta 0:00:07
   ----------------- ---------------------- 4.7/11.0 MB 928.9 kB/s eta 0:00:07
   ----------------- ---------------------- 4.8/11.0 MB 930.9 kB/s eta 0:00:07
   ----------------- ---------------------- 4.8/11.0 MB 930.9 kB/s eta 0:00:07
   ----------------- ---------------------- 4.8/11.0 MB 930.9 kB/s eta 0:00:07
   ----------------- ---------------------- 4.8/11.0 MB 930.9 kB/s eta 0:00:07
   ----------------- ---------------------- 4.8/11.0 MB 930.9 kB/s eta 0:00:07
   ----------------- ---------------------- 4.8/11.0 MB 930.9 kB/s eta 0:00:07
   ----------------- ---------------------- 4.8/11.0 MB 930.9 kB/s eta 0:00:07
   ------------------ --------------------- 5.0/11.0 MB 914.5 kB/s eta 0:00:07
   ------------------ --------------------- 5.0/11.0 MB 918.7 kB/s eta 0:00:07
   ------------------ --------------------- 5.1/11.0 MB 917.5 kB/s eta 0:00:07
   ------------------ --------------------- 5.1/11.0 MB 915.4 kB/s eta 0:00:07
   ------------------ --------------------- 5.2/11.0 MB 913.2 kB/s eta 0:00:07
   ------------------- -------------------- 5.2/11.0 MB 916.5 kB/s eta 0:00:07
   ------------------- -------------------- 5.3/11.0 MB 916.1 kB/s eta 0:00:07
   ------------------- -------------------- 5.3/11.0 MB 916.1 kB/s eta 0:00:07
   ------------------- -------------------- 5.3/11.0 MB 909.1 kB/s eta 0:00:07
   ------------------- -------------------- 5.3/11.0 MB 909.6 kB/s eta 0:00:07
   ------------------- -------------------- 5.3/11.0 MB 909.6 kB/s eta 0:00:07
   ------------------- -------------------- 5.3/11.0 MB 909.6 kB/s eta 0:00:07
   ------------------- -------------------- 5.3/11.0 MB 909.6 kB/s eta 0:00:07
   ------------------- -------------------- 5.3/11.0 MB 909.6 kB/s eta 0:00:07
   ------------------- -------------------- 5.3/11.0 MB 909.6 kB/s eta 0:00:07
   ------------------- -------------------- 5.3/11.0 MB 909.6 kB/s eta 0:00:07
   ------------------- -------------------- 5.5/11.0 MB 882.2 kB/s eta 0:00:07
   -------------------- ------------------- 5.6/11.0 MB 890.3 kB/s eta 0:00:07
   -------------------- ------------------- 5.6/11.0 MB 886.3 kB/s eta 0:00:07
   -------------------- ------------------- 5.6/11.0 MB 886.3 kB/s eta 0:00:07
   -------------------- ------------------- 5.6/11.0 MB 886.3 kB/s eta 0:00:07
   -------------------- ------------------- 5.6/11.0 MB 886.3 kB/s eta 0:00:07
   -------------------- ------------------- 5.6/11.0 MB 886.3 kB/s eta 0:00:07
   -------------------- ------------------- 5.6/11.0 MB 864.5 kB/s eta 0:00:07
   -------------------- ------------------- 5.7/11.0 MB 861.4 kB/s eta 0:00:07
   -------------------- ------------------- 5.7/11.0 MB 860.9 kB/s eta 0:00:07
   -------------------- ------------------- 5.7/11.0 MB 860.9 kB/s eta 0:00:07
   -------------------- ------------------- 5.7/11.0 MB 860.9 kB/s eta 0:00:07
   -------------------- ------------------- 5.7/11.0 MB 860.9 kB/s eta 0:00:07
   -------------------- ------------------- 5.7/11.0 MB 860.9 kB/s eta 0:00:07
   --------------------- ------------------ 5.8/11.0 MB 845.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.8/11.0 MB 845.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.8/11.0 MB 845.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.8/11.0 MB 845.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.8/11.0 MB 845.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.8/11.0 MB 845.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.8/11.0 MB 845.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.9/11.0 MB 821.4 kB/s eta 0:00:07
   --------------------- ------------------ 5.9/11.0 MB 817.2 kB/s eta 0:00:07
   --------------------- ------------------ 5.9/11.0 MB 817.2 kB/s eta 0:00:07
   --------------------- ------------------ 5.9/11.0 MB 812.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.9/11.0 MB 812.5 kB/s eta 0:00:07
   --------------------- ------------------ 5.9/11.0 MB 812.5 kB/s eta 0:00:07
   --------------------- ------------------ 6.0/11.0 MB 799.6 kB/s eta 0:00:07
   --------------------- ------------------ 6.0/11.0 MB 802.4 kB/s eta 0:00:07
   --------------------- ------------------ 6.0/11.0 MB 796.5 kB/s eta 0:00:07
   ---------------------- ----------------- 6.0/11.0 MB 795.9 kB/s eta 0:00:07
   ---------------------- ----------------- 6.1/11.0 MB 793.5 kB/s eta 0:00:07
   ---------------------- ----------------- 6.1/11.0 MB 794.2 kB/s eta 0:00:07
   ---------------------- ----------------- 6.1/11.0 MB 793.1 kB/s eta 0:00:07
   ---------------------- ----------------- 6.2/11.0 MB 793.6 kB/s eta 0:00:07
   ---------------------- ----------------- 6.2/11.0 MB 793.2 kB/s eta 0:00:07
   ---------------------- ----------------- 6.2/11.0 MB 791.9 kB/s eta 0:00:06
   ---------------------- ----------------- 6.3/11.0 MB 792.7 kB/s eta 0:00:06
   ---------------------- ----------------- 6.3/11.0 MB 790.4 kB/s eta 0:00:06
   ----------------------- ---------------- 6.3/11.0 MB 792.3 kB/s eta 0:00:06
   ----------------------- ---------------- 6.4/11.0 MB 791.3 kB/s eta 0:00:06
   ----------------------- ---------------- 6.4/11.0 MB 790.8 kB/s eta 0:00:06
   ----------------------- ---------------- 6.4/11.0 MB 791.5 kB/s eta 0:00:06
   ----------------------- ---------------- 6.5/11.0 MB 789.2 kB/s eta 0:00:06
   ----------------------- ---------------- 6.5/11.0 MB 790.9 kB/s eta 0:00:06
   ----------------------- ---------------- 6.6/11.0 MB 793.1 kB/s eta 0:00:06
   ----------------------- ---------------- 6.6/11.0 MB 789.7 kB/s eta 0:00:06
   ------------------------ --------------- 6.6/11.0 MB 787.4 kB/s eta 0:00:06
   ------------------------ --------------- 6.6/11.0 MB 788.2 kB/s eta 0:00:06
   ------------------------ --------------- 6.7/11.0 MB 784.8 kB/s eta 0:00:06
   ------------------------ --------------- 6.7/11.0 MB 784.3 kB/s eta 0:00:06
   ------------------------ --------------- 6.7/11.0 MB 783.4 kB/s eta 0:00:06
   ------------------------ --------------- 6.8/11.0 MB 785.3 kB/s eta 0:00:06
   ------------------------ --------------- 6.8/11.0 MB 785.8 kB/s eta 0:00:06
   ------------------------ --------------- 6.8/11.0 MB 787.6 kB/s eta 0:00:06
   ------------------------- -------------- 6.9/11.0 MB 788.1 kB/s eta 0:00:06
   ------------------------- -------------- 7.0/11.0 MB 790.7 kB/s eta 0:00:06
   ------------------------- -------------- 7.0/11.0 MB 789.0 kB/s eta 0:00:06
   ------------------------- -------------- 7.0/11.0 MB 789.0 kB/s eta 0:00:06
   ------------------------- -------------- 7.0/11.0 MB 789.0 kB/s eta 0:00:06
   ------------------------- -------------- 7.0/11.0 MB 789.0 kB/s eta 0:00:06
   ------------------------- -------------- 7.0/11.0 MB 774.8 kB/s eta 0:00:06
   ------------------------- -------------- 7.0/11.0 MB 777.8 kB/s eta 0:00:06
   ------------------------- -------------- 7.1/11.0 MB 775.9 kB/s eta 0:00:06
   ------------------------- -------------- 7.1/11.0 MB 775.4 kB/s eta 0:00:06
   ------------------------- -------------- 7.1/11.0 MB 774.7 kB/s eta 0:00:05
   -------------------------- ------------- 7.2/11.0 MB 777.8 kB/s eta 0:00:05
   -------------------------- ------------- 7.2/11.0 MB 774.5 kB/s eta 0:00:05
   -------------------------- ------------- 7.2/11.0 MB 775.3 kB/s eta 0:00:05
   -------------------------- ------------- 7.3/11.0 MB 776.6 kB/s eta 0:00:05
   -------------------------- ------------- 7.3/11.0 MB 777.1 kB/s eta 0:00:05
   -------------------------- ------------- 7.4/11.0 MB 778.9 kB/s eta 0:00:05
   --------------------------- ------------ 7.4/11.0 MB 781.5 kB/s eta 0:00:05
   --------------------------- ------------ 7.5/11.0 MB 783.9 kB/s eta 0:00:05
   --------------------------- ------------ 7.5/11.0 MB 782.4 kB/s eta 0:00:05
   --------------------------- ------------ 7.6/11.0 MB 785.0 kB/s eta 0:00:05
   --------------------------- ------------ 7.6/11.0 MB 787.5 kB/s eta 0:00:05
   ---------------------------- ----------- 7.7/11.0 MB 790.8 kB/s eta 0:00:05
   ---------------------------- ----------- 7.8/11.0 MB 794.9 kB/s eta 0:00:05
   ---------------------------- ----------- 7.8/11.0 MB 795.0 kB/s eta 0:00:04
   ---------------------------- ----------- 7.9/11.0 MB 799.5 kB/s eta 0:00:04
   ---------------------------- ----------- 8.0/11.0 MB 800.9 kB/s eta 0:00:04
   ----------------------------- ---------- 8.0/11.0 MB 803.5 kB/s eta 0:00:04
   ----------------------------- ---------- 8.0/11.0 MB 804.1 kB/s eta 0:00:04
   ----------------------------- ---------- 8.1/11.0 MB 805.2 kB/s eta 0:00:04
   ----------------------------- ---------- 8.2/11.0 MB 807.3 kB/s eta 0:00:04
   ----------------------------- ---------- 8.2/11.0 MB 806.6 kB/s eta 0:00:04
   ----------------------------- ---------- 8.2/11.0 MB 806.4 kB/s eta 0:00:04
   ------------------------------ --------- 8.3/11.0 MB 808.2 kB/s eta 0:00:04
   ------------------------------ --------- 8.3/11.0 MB 809.5 kB/s eta 0:00:04
   ------------------------------ --------- 8.4/11.0 MB 812.8 kB/s eta 0:00:04
   ------------------------------ --------- 8.5/11.0 MB 817.0 kB/s eta 0:00:04
   ------------------------------- -------- 8.6/11.0 MB 821.2 kB/s eta 0:00:03
   ------------------------------- -------- 8.6/11.0 MB 820.5 kB/s eta 0:00:03
   ------------------------------- -------- 8.7/11.0 MB 824.6 kB/s eta 0:00:03
   ------------------------------- -------- 8.7/11.0 MB 825.3 kB/s eta 0:00:03
   ------------------------------- -------- 8.7/11.0 MB 825.3 kB/s eta 0:00:03
   -------------------------------- ------- 8.8/11.0 MB 824.5 kB/s eta 0:00:03
   -------------------------------- ------- 8.8/11.0 MB 823.8 kB/s eta 0:00:03
   -------------------------------- ------- 8.9/11.0 MB 827.8 kB/s eta 0:00:03
   -------------------------------- ------- 8.9/11.0 MB 828.5 kB/s eta 0:00:03
   -------------------------------- ------- 8.9/11.0 MB 824.6 kB/s eta 0:00:03
   -------------------------------- ------- 8.9/11.0 MB 824.6 kB/s eta 0:00:03
   -------------------------------- ------- 9.0/11.0 MB 824.9 kB/s eta 0:00:03
   -------------------------------- ------- 9.0/11.0 MB 824.9 kB/s eta 0:00:03
   --------------------------------- ------ 9.1/11.0 MB 822.5 kB/s eta 0:00:03
   --------------------------------- ------ 9.1/11.0 MB 823.6 kB/s eta 0:00:03
   --------------------------------- ------ 9.2/11.0 MB 825.6 kB/s eta 0:00:03
   --------------------------------- ------ 9.2/11.0 MB 825.6 kB/s eta 0:00:03
   --------------------------------- ------ 9.2/11.0 MB 825.6 kB/s eta 0:00:03

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
import numpy as np

In [6]:
np.random.randint(35, 100, (50, 6))

array([[75, 58, 35, 71, 68, 37],
       [93, 59, 78, 93, 64, 61],
       [92, 91, 52, 86, 46, 52],
       [77, 63, 71, 54, 40, 72],
       [94, 72, 92, 69, 37, 36],
       [96, 44, 48, 38, 92, 55],
       [78, 51, 73, 37, 92, 39],
       [40, 70, 54, 57, 88, 94],
       [90, 62, 53, 50, 97, 69],
       [46, 73, 98, 66, 40, 80],
       [42, 88, 80, 82, 63, 93],
       [45, 94, 86, 51, 97, 87],
       [36, 41, 63, 52, 86, 53],
       [83, 54, 89, 55, 44, 67],
       [93, 50, 95, 87, 78, 40],
       [61, 56, 57, 56, 39, 70],
       [67, 70, 49, 63, 64, 78],
       [70, 77, 82, 87, 73, 90],
       [91, 75, 57, 46, 80, 84],
       [74, 53, 57, 46, 49, 44],
       [45, 75, 57, 47, 92, 56],
       [84, 45, 47, 84, 55, 55],
       [57, 87, 73, 98, 54, 89],
       [85, 54, 50, 78, 83, 94],
       [75, 52, 77, 77, 52, 83],
       [90, 98, 72, 58, 52, 42],
       [68, 74, 77, 59, 77, 72],
       [98, 49, 86, 51, 69, 52],
       [55, 69, 72, 43, 70, 35],
       [86, 40, 79, 83, 64, 77],
       [56, 95, 70, 72, 80, 59],
       [42, 99, 76, 52, 65, 79],
       [35, 43, 74, 75, 45, 94],
       [52, 63, 89, 49, 83, 57],
       [41, 89, 49, 41, 64, 94],
       [84, 67, 97, 40, 72, 97],
       [39, 88, 55, 85, 62, 50],
       [50, 62, 47, 46, 83, 47],
       [61, 37, 39, 97, 80, 86],
       [51, 39, 88, 91, 90, 53],
       [53, 65, 92, 63, 79, 95],
       [42, 83, 94, 36, 44, 84],
       [97, 54, 45, 59, 68, 99],
       [53, 37, 41, 38, 70, 49],
       [75, 43, 65, 79, 40, 87],
       [35, 62, 56, 85, 96, 97],
       [51, 60, 94, 66, 68, 53],
       [80, 56, 58, 48, 57, 41],
       [79, 47, 40, 69, 42, 80],
       [50, 35, 74, 60, 56, 66]], dtype=int32)

In [10]:
stud_data = pd.DataFrame(np.random.randint(35, 100, (50, 6)), columns = ['m1', 'm2', 'm3', 'm4', 'm5', 'm6'])
stud_data

    m1  m2  m3  m4  m5  m6
0   39  70  67  48  85  55
1   88  80  75  67  45  68
2   57  48  84  81  82  51
3   38  47  62  41  37  56
4   43  97  54  97  48  59
5   63  46  53  91  99  50
6   50  44  58  88  59  85
7   92  77  71  54  48  76
8   70  59  90  59  83  90
9   85  56  49  41  67  88
10  97  39  74  95  37  89
11  40  63  97  69  42  90
12  42  58  44  64  62  69
13  49  58  60  61  37  43
14  76  38  52  56  84  59
15  86  94  40  45  71  60
16  97  77  59  55  63  42
17  68  54  49  76  90  92
18  74  93  91  41  67  73
19  60  63  80  41  75  91
20  61  82  89  51  39  38
21  96  65  54  35  56  60
22  92  50  60  74  67  40
23  47  45  84  72  99  48
24  88  76  59  98  37  60
25  39  37  76  47  46  88
26  46  86  52  55  93  63
27  85  47  64  40  83  72
28  46  78  53  58  84  40
29  87  40  95  76  91  83
30  91  70  69  85  79  41
31  61  97  91  38  37  54
32  97  73  80  93  79  96
33  94  46  84  92  97  62
34  84  93  50  68  61  80
35  90  82  76  95  41  66
36  37  61  87  43  73  55
37  69  75  81  47  95  83
38  90  92  44  48  80  69
39  41  71  93  95  72  36
40  88  85  57  67  48  48
41  60  74  47  99  62  44
42  54  63  96  98  56  37
43  95  90  52  85  54  98
44  55  78  63  81  90  64
45  64  69  91  80  87  78
46  92  48  40  63  44  53
47  56  69  55  88  56  89
48  95  84  98  91  44  85
49  35  53  55  39  91  77

In [21]:
stud_data['Total_marks'] = stud_data['m1'] + stud_data['m2'] + stud_data['m3'] + stud_data['m4'] + stud_data['m5'] + stud_data['m6']

In [16]:
stud_data

    m1  m2  m3  m4  m5  m6  Totsl_marks
0   39  70  67  48  85  55          364
1   88  80  75  67  45  68          423
2   57  48  84  81  82  51          403
3   38  47  62  41  37  56          281
4   43  97  54  97  48  59          398
5   63  46  53  91  99  50          402
6   50  44  58  88  59  85          384
7   92  77  71  54  48  76          418
8   70  59  90  59  83  90          451
9   85  56  49  41  67  88          386
10  97  39  74  95  37  89          431
11  40  63  97  69  42  90          401
12  42  58  44  64  62  69          339
13  49  58  60  61  37  43          308
14  76  38  52  56  84  59          365
15  86  94  40  45  71  60          396
16  97  77  59  55  63  42          393
17  68  54  49  76  90  92          429
18  74  93  91  41  67  73          439
19  60  63  80  41  75  91          410
20  61  82  89  51  39  38          360
21  96  65  54  35  56  60          366
22  92  50  60  74  67  40          383
23  47  45  84  72  99  48          395
24  88  76  59  98  37  60          418
25  39  37  76  47  46  88          333
26  46  86  52  55  93  63          395
27  85  47  64  40  83  72          391
28  46  78  53  58  84  40          359
29  87  40  95  76  91  83          472
30  91  70  69  85  79  41          435
31  61  97  91  38  37  54          378
32  97  73  80  93  79  96          518
33  94  46  84  92  97  62          475
34  84  93  50  68  61  80          436
35  90  82  76  95  41  66          450
36  37  61  87  43  73  55          356
37  69  75  81  47  95  83          450
38  90  92  44  48  80  69          423
39  41  71  93  95  72  36          408
40  88  85  57  67  48  48          393
41  60  74  47  99  62  44          386
42  54  63  96  98  56  37          404
43  95  90  52  85  54  98          474
44  55  78  63  81  90  64          431
45  64  69  91  80  87  78          469
46  92  48  40  63  44  53          340
47  56  69  55  88  56  89          413
48  95  84  98  91  44  85          497
49  35  53  55  39  91  77          350

In [24]:
stud_data['percentage'] = stud_data['Total_marks'] / 6
stud_data

    m1  m2  m3  m4  m5  m6  Totsl_marks  Total_marks  percentage
0   39  70  67  48  85  55          364          364   60.666667
1   88  80  75  67  45  68          423          423   70.500000
2   57  48  84  81  82  51          403          403   67.166667
3   38  47  62  41  37  56          281          281   46.833333
4   43  97  54  97  48  59          398          398   66.333333
5   63  46  53  91  99  50          402          402   67.000000
6   50  44  58  88  59  85          384          384   64.000000
7   92  77  71  54  48  76          418          418   69.666667
8   70  59  90  59  83  90          451          451   75.166667
9   85  56  49  41  67  88          386          386   64.333333
10  97  39  74  95  37  89          431          431   71.833333
11  40  63  97  69  42  90          401          401   66.833333
12  42  58  44  64  62  69          339          339   56.500000
13  49  58  60  61  37  43          308          308   51.333333
14  76  38  52  56  84  59          365          365   60.833333
15  86  94  40  45  71  60          396          396   66.000000
16  97  77  59  55  63  42          393          393   65.500000
17  68  54  49  76  90  92          429          429   71.500000
18  74  93  91  41  67  73          439          439   73.166667
19  60  63  80  41  75  91          410          410   68.333333
20  61  82  89  51  39  38          360          360   60.000000
21  96  65  54  35  56  60          366          366   61.000000
22  92  50  60  74  67  40          383          383   63.833333
23  47  45  84  72  99  48          395          395   65.833333
24  88  76  59  98  37  60          418          418   69.666667
25  39  37  76  47  46  88          333          333   55.500000
26  46  86  52  55  93  63          395          395   65.833333
27  85  47  64  40  83  72          391          391   65.166667
28  46  78  53  58  84  40          359          359   59.833333
29  87  40  95  76  91  83          472          472   78.666667
30  91  70  69  85  79  41          435          435   72.500000
31  61  97  91  38  37  54          378          378   63.000000
32  97  73  80  93  79  96          518          518   86.333333
33  94  46  84  92  97  62          475          475   79.166667
34  84  93  50  68  61  80          436          436   72.666667
35  90  82  76  95  41  66          450          450   75.000000
36  37  61  87  43  73  55          356          356   59.333333
37  69  75  81  47  95  83          450          450   75.000000
38  90  92  44  48  80  69          423          423   70.500000
39  41  71  93  95  72  36          408          408   68.000000
40  88  85  57  67  48  48          393          393   65.500000
41  60  74  47  99  62  44          386          386   64.333333
42  54  63  96  98  56  37          404          404   67.333333
43  95  90  52  85  54  98          474          474   79.000000
44  55  78  63  81  90  64          431          431   71.833333
45  64  69  91  80  87  78          469          469   78.166667
46  92  48  40  63  44  53          340          340   56.666667
47  56  69  55  88  56  89          413          413   68.833333
48  95  84  98  91  44  85          497          497   82.833333
49  35  53  55  39  91  77          350          350   58.333333

In [25]:
stud_data['percentage'].max()

np.float64(86.33333333333333)

### Merging

In [50]:
emp = pd.DataFrame({'name': ['Shankar', 'Pragati', 'Archita', 'pratik', 'prashant'],
                   'Age': ['22', '23', '24', '25', '26'],
                   'Salary': [45000, 46000, 47000, 48000, 49000],
                   'DID': [1, 2, 3, 4, 5]})
emp

       name Age  Salary  DID
0   Shankar  22   45000    1
1   Pragati  23   46000    2
2   Archita  24   47000    3
3    pratik  25   48000    4
4  prashant  26   49000    5

In [51]:
dept = pd.DataFrame({'ID': [1, 2, 3, 4],
                     'Dname':['Software development', 'Data Analyst', 'HR', 'Admin',]})
dept

   ID                 Dname
0   1  Software development
1   2          Data Analyst
2   3                    HR
3   4                 Admin

In [52]:
pd.merge(emp, dept, left_on= 'DID', right_on = 'ID', how = 'inner')

      name Age  Salary  DID  ID                 Dname
0  Shankar  22   45000    1   1  Software development
1  Pragati  23   46000    2   2          Data Analyst
2  Archita  24   47000    3   3                    HR
3   pratik  25   48000    4   4                 Admin

In [53]:
pd.merge(emp, dept, left_on= 'DID', right_on = 'ID', how = 'outer')

       name Age  Salary  DID   ID                 Dname
0   Shankar  22   45000    1  1.0  Software development
1   Pragati  23   46000    2  2.0          Data Analyst
2   Archita  24   47000    3  3.0                    HR
3    pratik  25   48000    4  4.0                 Admin
4  prashant  26   49000    5  NaN                   NaN

In [54]:
pd.merge(emp, dept, left_on = 'DID' , right_on = 'ID', how = 'left')

       name Age  Salary  DID   ID                 Dname
0   Shankar  22   45000    1  1.0  Software development
1   Pragati  23   46000    2  2.0          Data Analyst
2   Archita  24   47000    3  3.0                    HR
3    pratik  25   48000    4  4.0                 Admin
4  prashant  26   49000    5  NaN                   NaN

In [55]:
pd.merge(emp, dept, left_on = 'DID' , right_on = 'ID', how = 'right')

      name Age  Salary  DID  ID                 Dname
0  Shankar  22   45000    1   1  Software development
1  Pragati  23   46000    2   2          Data Analyst
2  Archita  24   47000    3   3                    HR
3   pratik  25   48000    4   4                 Admin

In [56]:
emp

       name Age  Salary  DID
0   Shankar  22   45000    1
1   Pragati  23   46000    2
2   Archita  24   47000    3
3    pratik  25   48000    4
4  prashant  26   49000    5

In [57]:
emp

       name Age  Salary  DID
0   Shankar  22   45000    1
1   Pragati  23   46000    2
2   Archita  24   47000    3
3    pratik  25   48000    4
4  prashant  26   49000    5

In [59]:
emp.describe()

            Salary       DID
count      5.00000  5.000000
mean   47000.00000  3.000000
std     1581.13883  1.581139
min    45000.00000  1.000000
25%    46000.00000  2.000000
50%    47000.00000  3.000000
75%    48000.00000  4.000000
max    49000.00000  5.000000

In [60]:
emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   Age     5 non-null      object
 2   Salary  5 non-null      int64
 3   DID     5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [13]:
stud = pd.DataFrame({"Name": ["Shankar", "Pragati", "Pratik", "Dipali"],
                    "Age": ["21", "22", "22", "21"],
                    "Marks": [98, 99, 98, 99],
                    "SID": [101, 102, 103, 104]})
stud

      Name Age  Marks  SID
0  Shankar  21     98  101
1  Pragati  22     99  102
2   Pratik  22     98  103
3   Dipali  21     99  104

In [24]:
deptt = pd.DataFrame({"DID": [101, 102, 103],
                    "Dname": ["SW","HR", "SALES"]})
deptt

   DID  Dname
0  101     SW
1  102     HR
2  103  SALES

In [25]:
pd.merge(stud, deptt, left_on= "SID", right_on = "DID", how = "inner")

      Name Age  Marks  SID  DID  Dname
0  Shankar  21     98  101  101     SW
1  Pragati  22     99  102  102     HR
2   Pratik  22     98  103  103  SALES

In [26]:
pd.merge(stud, deptt, left_on= "SID", right_on = "DID", how = "outer")

      Name Age  Marks  SID    DID  Dname
0  Shankar  21     98  101  101.0     SW
1  Pragati  22     99  102  102.0     HR
2   Pratik  22     98  103  103.0  SALES
3   Dipali  21     99  104    NaN    NaN

In [27]:
pd.merge(stud, deptt, left_on= "SID", right_on = "DID", how = "left")

      Name Age  Marks  SID    DID  Dname
0  Shankar  21     98  101  101.0     SW
1  Pragati  22     99  102  102.0     HR
2   Pratik  22     98  103  103.0  SALES
3   Dipali  21     99  104    NaN    NaN

In [28]:
pd.merge(stud, deptt, left_on= "SID", right_on = "DID", how = "right")

      Name Age  Marks  SID  DID  Dname
0  Shankar  21     98  101  101     SW
1  Pragati  22     99  102  102     HR
2   Pratik  22     98  103  103  SALES

In [29]:
students = pd.DataFrame({"Name": ["Shankar", "Pragati", "Pratik", "Dipali"],
                        "Age": ["21", "22", "22", "21"],
                        "Marks": [98, 99, 98, 99],
                        "SIDD": [101, 102, 103, 104]})
students

      Name  Age  Marks  SIDD
0  Shankar   21     98   101
1  Pragati   22     99   102
2   Pratik   22     98   103
3   Dipali   21     99   104

In [30]:
department = pd.DataFrame({"Dept_ID":[1, 2, 3],
                          "Dept_Name": ["SW", "HR", "ADMIN"]})
department

   Dept_ID Dept_Name
0        1        SW
1        2        HR
2        3     ADMIN

In [34]:
pd.merge(students, department , left_on= "SIDD", right_on="Dept_ID", how="inner")

Empty DataFrame
Columns: [Name, Age, Marks, SIDD, Dept_ID, Dept_Name]
Index: []

In [35]:
pd.merge(students, department , left_on= "SIDD", right_on="Dept_ID", how="right")

  Name  Age  Marks  SIDD  Dept_ID Dept_Name
0  NaN  NaN    NaN   NaN        1        SW
1  NaN  NaN    NaN   NaN        2        HR
2  NaN  NaN    NaN   NaN        3     ADMIN

In [36]:
pd.merge(students, department , left_on= "SIDD", right_on="Dept_ID", how="left")

      Name  Age  Marks  SIDD  Dept_ID Dept_Name
0  Shankar   21     98   101      NaN       NaN
1  Pragati   22     99   102      NaN       NaN
2   Pratik   22     98   103      NaN       NaN
3   Dipali   21     99   104      NaN       NaN