In [1]:
import pandas as pd

In [4]:
stud_res = pd.read_csv("C:/Users/ADMIN/Desktop/FBS/Data Analysis/data set/student_result.csv")
stud_res

,Student ID,Section,Class,Study hrs,Sleeping hrs,Social Medic,Mobile Game,Percentage
0,1001,A,10,2,9,3,5,50
1,1002,B,10,6,8,2,0,80
2,1003,A,10,3,8,2,4,60
3,1004,C,11,0,10,1,5,45
4,1005,C,11,4,7,2,0,75
5,1006,A,11,10,7,0,0,96
6,1007,B,12,4,6,0,0,80
7,1008,A,12,10,6,2,0,90
8,1009,B,12,2,8,2,4,60
9,1010,C,12,6,9,1,0,85

### Group by

In [6]:
class_res = stud_res.groupby(['Class'])
class_res

In [8]:
df = pd.DataFrame(class_res)
df

       0                                                  1
0  (10,)     Student ID Section  Class  Study hrs  Sleep...
1  (11,)     Student ID Section  Class  Study hrs  Sleep...
2  (12,)     Student ID Section  Class  Study hrs  Sleep...

In [2]:
class_res.get_group(10)
class_res

NameError: name 'class_res' is not defined

In [3]:
class_res.get_group(12)

NameError: name 'class_res' is not defined

In [14]:
Class_res['study hrs'].sum()

NameError: name 'Class_res' is not defined

In [13]:
class_res.count()

,Student ID,Section,Study hrs,Sleeping hrs,Social Medic,Mobile Game,Percentage
Class,,,,,,,
10,3,3,3,3,3,3,3
11,3,3,3,3,3,3,3
12,4,4,4,4,4,4,4

In [15]:
class_res['Social Medic'].min()

Class
10    2
11    0
12    0
Name: Social Medic, dtype: int64

In [16]:
df

       0                                                  1
0  (10,)     Student ID Section  Class  Study hrs  Sleep...
1  (11,)     Student ID Section  Class  Study hrs  Sleep...
2  (12,)     Student ID Section  Class  Study hrs  Sleep...

In [17]:
stud_res

,Student ID,Section,Class,Study hrs,Sleeping hrs,Social Medic,Mobile Game,Percentage
0,1001,A,10,2,9,3,5,50
1,1002,B,10,6,8,2,0,80
2,1003,A,10,3,8,2,4,60
3,1004,C,11,0,10,1,5,45
4,1005,C,11,4,7,2,0,75
5,1006,A,11,10,7,0,0,96
6,1007,B,12,4,6,0,0,80
7,1008,A,12,10,6,2,0,90
8,1009,B,12,2,8,2,4,60
9,1010,C,12,6,9,1,0,85

In [18]:
class_res['Sleeping hrs'].max()

Class
10     9
11    10
12     9
Name: Sleeping hrs, dtype: int64

In [19]:
class_res['Study hrs'].mean()

Class
10    3.666667
11    4.666667
12    5.500000
Name: Study hrs, dtype: float64

In [20]:
class_res.groups

{10: [0, 1, 2], 11: [3, 4, 5], 12: [6, 7, 8, 9]}

In [21]:
list(class_res)

[((10,),
     Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
  0        1001       A     10          2             9             3
  1        1002       B     10          6             8             2
  2        1003       A     10          3             8             2

     Mobile Game  Percentage
  0            5          50
  1            0          80
  2            4          60  ),
 ((11,),
     Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
  3        1004       C     11          0            10             1
  4        1005       C     11          4             7             2
  5        1006       A     11         10             7             0

     Mobile Game  Percentage
  3            5          45
  4            0          75
  5            0          96  ),
 ((12,),
     Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
  6        1007       B     12          4             6             0
  7        1008       A     12         10             6             2
  8        1009       B     12          2             8             2
  9        1010       C     12          6             9             1

     Mobile Game  Percentage
  6            0          80
  7            0          90
  8            4          60
  9            0          85  )]

In [22]:
dict(list(class_res))

{(10,):    Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
 0        1001       A     10          2             9             3
 1        1002       B     10          6             8             2
 2        1003       A     10          3             8             2

    Mobile Game  Percentage
 0            5          50
 1            0          80
 2            4          60  ,
 (11,):    Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
 3        1004       C     11          0            10             1
 4        1005       C     11          4             7             2
 5        1006       A     11         10             7             0

    Mobile Game  Percentage
 3            5          45
 4            0          75
 5            0          96  ,
 (12,):    Student ID Section  Class  Study hrs  Sleeping hrs  Social Medic  \
 6        1007       B     12          4             6             0
 7        1008       A     12         10             6             2
 8        1009       B     12          2             8             2
 9        1010       C     12          6             9             1

    Mobile Game  Percentage
 6            0          80
 7            0          90
 8            4          60
 9            0          85  }

### Handling missing values

In [4]:
stud_10 = pd.read_csv(C:/Users/ADMIN/Desktop/FBS/Data Analysis/data set)
stud_10

SyntaxError: invalid syntax (3211330836.py, line 1)

In [29]:
stud_10.dropna(axis = 1)

NameError: name 'stud_10' is not defined

In [30]:
stud_10.fillna(0)

NameError: name 'stud_10' is not defined

In [35]:
stud_10

NameError: name 'stud_10' is not defined

In [37]:
stud_10.fillna(method = 'ffill')

NameError: name 'stud_10' is not defined

In [36]:
stud_10.fillna(method = 'bfill')

NameError: name 'stud_10' is not defined

In [38]:
stud_10.isna()

NameError: name 'stud_10' is not defined

In [39]:
stud_10.bfill()

NameError: name 'stud_10' is not defined

In [40]:
stud_10.ffill()

NameError: name 'stud_10' is not defined

In [41]:
stud_10.interpolate()

NameError: name 'stud_10' is not defined

In [ ]:
stud = pd.DataFrame(stud_res.gr)